### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by jareis** [getupcloud/python-mailgunlog#1]
Hello,

There is something wrong with the request 
```
mailgunlog -d 2 -v samples.mailgun.org key-3ax6xnjp29jd6fds4gc373sgvjxteol0
# BEGIN DATE: Wed, 16 Dec 2015 00:00:00 -0000
# END DATE: Fri, 18 Dec 2015 23:59:59 -0000
Traceback (most recent call last):
  File "/usr/local/bin/mailgunlog", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/mailgunlog/mailgunlog.py", line 150, in main
    for log in logs(domain=domain, api_key=api_key, begin=begin, end=end):
  File "/Library/Python/2.7/site-packages/mailgunlog/mailgunlog.py", line 27, in logs
    data = req.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

if making a browser request (or cURL) to
```
https://api:key-3ax6xnjp29jd6fds4gc373sgvjxteol0@api.mailgun.net/v3/samples.mailgun.org/log
```
works fine.

**Comment by caruccio** [comment]
Sorry for the late response. Github simply doesn't send notifications anymore to my email, even I'm subscribing to this repo.

The problem was fixed. Also, some minor additions:
- python3 support
- new flag -V|--version
- Now -v|--verbose prints request url and response status code

Please see if it's working for you now.
