### ISSUE TITLE
mysql problem

### ISSUE THREAD

**Issue by CS-sysadmins** [getupcloud/python-mailgunlog#4]
Hello

On new install, I have this
```
13:13:22.944 [info] GET /
13:13:22.970 [info] Sent 200 in 25ms
13:13:27.016 [info] POST /trigger_run
13:13:27.020 [info] Sent 302 in 3ms
13:13:27.025 [info] GET /
13:13:27.029 [info] Sent 200 in 4ms
13:13:28.089 [error] Task #PID<0.3404.0> started from #PID<0.3403.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, 401, "{\"message\":\"Invalid private key\"}"} of type Tuple. This protocol is implemented for the following type(s): Pager.Page, Ecto.Adapters.SQL.Stream, DBConnection.PrepareStream, DBConnection.Stream, HashSet, Date.Range, Map, Stream, Range, List, GenEvent.Stream, MapSet, HashDict, IO.Stream, Function, File.Stream
    (elixir 1.11.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.11.0) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.11.0) lib/enum.ex:3461: Enum.map/2
    (mailgun_logger 0.2.0) lib/mailgun_logger/events/events.ex:77: MailgunLogger.Events.save_events/2
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.19295648/0 in MailgunLogger.run/0>
    Args: []
13:14:20.772 [info] GET /
13:14:20.781 [info] Sent 200 in 9ms

```
Maybe some problem with the new docker of mysql ?
I have 0 experience in docker, so treat me as newby

thanks

**Comment by CS-sysadmins** [comment]
my bad, wrong key
